Fix build with gcc-13
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/529520

FAILED: CMakeFiles/webos-hfp-service.dir/src/utils.cpp.o
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++  -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/include/libmount -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/include/blkid -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/include/gio-unix-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/git/src -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/build/Configured/src -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/git=/usr/src/debug/com.webos.service.hfp/1.0.0-32-r5  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/git=/usr/src/debug/com.webos.service.hfp/1.0.0-32-r5  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/build=/usr/src/debug/com.webos.service.hfp/1.0.0-32-r5  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/build=/usr/src/debug/com.webos.service.hfp/1.0.0-32-r5  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++0x -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/lib/glib-2.0/include -pthread -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/include/libmount -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/include/blkid -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/lib/glib-2.0/include -pthread -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/recipe-sysroot/usr/lib/glib-2.0/include -Wl,--no-undefined -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/build/Configured/src -DNDEBUG -MD -MT CMakeFiles/webos-hfp-service.dir/src/utils.cpp.o -MF CMakeFiles/webos-hfp-service.dir/src/utils.cpp.o.d -o CMakeFiles/webos-hfp-service.dir/src/utils.cpp.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/git/src/utils.cpp
In file included from TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/git/src/utils.cpp:22:
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.hfp/1.0.0-32-r5/git/src/utils.h:28:17: error: 'uint8_t' does not name a type
   28 | void dump(const uint8_t *data, size_t len, const char *ind);
      |                 ^~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-8053] CCC: Various build fixes

Change-Id: I18c5529a0ca26511f71ac9c0dd27025c0012a020
Reviewed-on: http://gpro.lge.com/c/webosose/com.webos.service.hfp/+/344554
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: <muralidhar.n@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Tested-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
(cherry picked from commit 9c55b5871b0a57b1e0ba2a2e65b8a2d2ef4d5299)
Reviewed-on: http://gpro.lge.com/c/webosose/com.webos.service.hfp/+/375569
Tested-by: <muralidhar.n@lge.com>